spring.application.name=family-wishing-bot

spring.datasource.url=${DB_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:family_bot}}
spring.datasource.username=${DB_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${DB_PASSWORD:${MYSQLPASSWORD:}}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.thymeleaf.cache=false
server.port=${PORT:8080}
