spring.application.name=family-wishing-bot

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:family_bot}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.thymeleaf.cache=false
server.port=${PORT:8080}
